import React, { useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { ArrowLeft, Calculator, Send, Copy, Download, BookOpen } from 'lucide-react'
import { getBedrockResponse } from '../services/bedrockService'

const MathCalculator = () => {
  const { user } = useAuth()
  const [problem, setProblem] = useState('')
  const [solution, setSolution] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [history, setHistory] = useState([])

  const sampleProblems = [
    {
      category: 'Algebra',
      problems: [
        'Solve: 2x² + 5x - 3 = 0',
        'Simplify: (x² - 4)/(x + 2)',
        'Find the roots of: x³ - 6x² + 11x - 6 = 0'
      ]
    },
    {
      category: 'Calculus',
      problems: [
        'Find the derivative of: f(x) = x³ + 2x² - 5x + 1',
        'Integrate: ∫(2x + 3)dx',
        'Find the limit: lim(x→0) (sin(x)/x)'
      ]
    },
    {
      category: 'Trigonometry',
      problems: [
        'Solve: sin(2x) = cos(x) for 0 ≤ x ≤ 2π',
        'Prove: sin²(x) + cos²(x) = 1',
        'Find all solutions: tan(x) = √3'
      ]
    },
    {
      category: 'Geometry',
      problems: [
        'Find the area of a triangle with sides 3, 4, 5',
        'Calculate the volume of a sphere with radius 5',
        'Find the equation of a line passing through (2,3) and (4,7)'
      ]
    },
    {
      category: 'Statistics',
      problems: [
        'Calculate mean, median, mode for: 2, 4, 4, 6, 8, 10, 12',
        'Find standard deviation for the dataset: 1, 3, 5, 7, 9',
        'Calculate probability of getting 2 heads in 3 coin tosses'
      ]
    }
  ]

  const handleSolve = async () => {
    if (!problem.trim() || isLoading) return

    setIsLoading(true)
    
    try {
      const response = await getBedrockResponse(problem, user)
      setSolution(response)
      
      // Add to history
      const newEntry = {
        id: Date.now(),
        problem: problem,
        solution: response,
        timestamp: new Date().toLocaleString()
      }
      setHistory(prev => [newEntry, ...prev.slice(0, 9)]) // Keep last 10
      
    } catch (error) {
      setSolution('Sorry, I encountered an error solving this problem. Please try again.')
    }
    
    setIsLoading(false)
  }

  const handleSampleProblem = (sampleProblem) => {
    setProblem(sampleProblem)
  }

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text)
    alert('Copied to clipboard!')
  }

  const downloadSolution = () => {
    if (!solution) return
    
    const content = `Problem: ${problem}\n\nSolution:\n${solution}\n\nGenerated by One Community Ely AI Assistant\nDate: ${new Date().toLocaleString()}`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'math-solution.txt'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-6 py-4">
          <div className="flex items-center space-x-4">
            <Link to="/ai-assistant" className="text-gray-600 hover:text-gray-800">
              <ArrowLeft className="h-6 w-6" />
            </Link>
            <div className="flex items-center space-x-3">
              <Calculator className="h-8 w-8 text-blue-600" />
              <div>
                <h1 className="text-xl font-bold text-gray-800">Advanced Math Calculator</h1>
                <p className="text-sm text-gray-600">Powered by AWS Bedrock AI - Solve complex mathematical problems</p>
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-6 py-8 max-w-6xl">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Calculator */}
          <div className="lg:col-span-2 space-y-6">
            {/* Input Section */}
            <div className="card">
              <h2 className="text-xl font-semibold mb-4">Enter Your Math Problem</h2>
              
              <div className="space-y-4">
                <textarea
                  value={problem}
                  onChange={(e) => setProblem(e.target.value)}
                  placeholder="Enter your mathematical problem here...

Examples:
• Solve: x² + 5x + 6 = 0
• Find derivative of: f(x) = x³ + 2x² - 5x + 1
• Integrate: ∫(2x + 3)dx
• Calculate: lim(x→0) (sin(x)/x)
• Simplify: (x² - 4)/(x + 2)
• Find area of triangle with sides 3, 4, 5"
                  className="w-full h-32 p-4 border border-gray-300 rounded-lg resize-none focus:outline-none focus:border-blue-500"
                />
                
                <div className="flex justify-between items-center">
                  <div className="text-sm text-gray-500">
                    Supports: Algebra, Calculus, Trigonometry, Geometry, Statistics
                  </div>
                  <button
                    onClick={handleSolve}
                    disabled={!problem.trim() || isLoading}
                    className="btn btn-primary flex items-center space-x-2 disabled:opacity-50"
                  >
                    {isLoading ? (
                      <div className="loading"></div>
                    ) : (
                      <Calculator className="h-5 w-5" />
                    )}
                    <span>{isLoading ? 'Solving...' : 'Solve Problem'}</span>
                  </button>
                </div>
              </div>
            </div>

            {/* Solution Display */}
            {solution && (
              <div className="card">
                <div className="flex justify-between items-center mb-4">
                  <h2 className="text-xl font-semibold">Solution</h2>
                  <div className="flex space-x-2">
                    <button
                      onClick={() => copyToClipboard(solution)}
                      className="btn btn-secondary flex items-center space-x-2"
                    >
                      <Copy className="h-4 w-4" />
                      <span>Copy</span>
                    </button>
                    <button
                      onClick={downloadSolution}
                      className="btn btn-secondary flex items-center space-x-2"
                    >
                      <Download className="h-4 w-4" />
                      <span>Download</span>
                    </button>
                  </div>
                </div>
                
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-sm font-medium text-gray-700 mb-2">Problem:</div>
                  <div className="text-gray-800 mb-4 p-2 bg-white rounded border-l-4 border-blue-500">
                    {problem}
                  </div>
                  
                  <div className="text-sm font-medium text-gray-700 mb-2">Solution:</div>
                  <div className="text-gray-800 whitespace-pre-wrap p-2 bg-white rounded border-l-4 border-green-500">
                    {solution}
                  </div>
                </div>
              </div>
            )}

            {/* History */}
            {history.length > 0 && (
              <div className="card">
                <h2 className="text-xl font-semibold mb-4">Recent Problems</h2>
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {history.map((entry) => (
                    <div key={entry.id} className="border border-gray-200 rounded-lg p-3 hover:bg-gray-50">
                      <div className="text-sm text-gray-500 mb-1">{entry.timestamp}</div>
                      <div className="text-sm font-medium text-gray-800 mb-2">{entry.problem}</div>
                      <button
                        onClick={() => {
                          setProblem(entry.problem)
                          setSolution(entry.solution)
                        }}
                        className="text-blue-600 hover:text-blue-800 text-sm"
                      >
                        View Solution →
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Sample Problems */}
            <div className="card">
              <h3 className="text-lg font-semibold mb-4">Sample Problems</h3>
              <div className="space-y-4">
                {sampleProblems.map((category) => (
                  <div key={category.category}>
                    <h4 className="font-medium text-gray-800 mb-2">{category.category}</h4>
                    <div className="space-y-2">
                      {category.problems.map((prob, index) => (
                        <button
                          key={index}
                          onClick={() => handleSampleProblem(prob)}
                          className="w-full text-left text-sm p-2 bg-gray-50 hover:bg-gray-100 rounded border text-gray-700"
                        >
                          {prob}
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Math Symbols Helper */}
            <div className="card">
              <h3 className="text-lg font-semibold mb-4">Math Symbols</h3>
              <div className="grid grid-cols-2 gap-2 text-sm">
                <div className="space-y-1">
                  <div><code>x²</code> - x squared</div>
                  <div><code>√x</code> - square root</div>
                  <div><code>∫</code> - integral</div>
                  <div><code>∂</code> - partial derivative</div>
                  <div><code>lim</code> - limit</div>
                </div>
                <div className="space-y-1">
                  <div><code>π</code> - pi</div>
                  <div><code>∞</code> - infinity</div>
                  <div><code>≤</code> - less than equal</div>
                  <div><code>≥</code> - greater than equal</div>
                  <div><code>≠</code> - not equal</div>
                </div>
              </div>
            </div>

            {/* Tips */}
            <div className="card">
              <h3 className="text-lg font-semibold mb-4">Tips</h3>
              <div className="text-sm text-gray-600 space-y-2">
                <p>• Be specific with your problems</p>
                <p>• Use standard mathematical notation</p>
                <p>• Include all given information</p>
                <p>• Ask for step-by-step solutions</p>
                <p>• Specify the type of answer needed</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default MathCalculator